### ISSUE TITLE
expected `Result<Reg16, OverflowError>`, found `Result<Reg16, OverflowError<u8>>`

### ISSUE THREAD

**Issue by vincenzopalazzo** [AluVM/rust-aluvm#104]
I was compiling a rgb dependencies inside my project but I have this error

```
   Compiling aluvm v0.10.6
   Compiling bp-consensus v0.10.11
error[E0308]: mismatched types
   --> /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aluvm-0.10.6/src/reg/indexes.rs:425:9
    |
424 |     fn try_from(value: Reg32) -> Result<Self, Self::Error> {
    |                                  ------------------------- expected `Result<Reg16, OverflowError>` because of return type
425 |         u4::try_from(value as u8).map(Reg16::from)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<Reg16, OverflowError>`, found `Result<Reg16, OverflowError<u8>>`
    |
    = note: expected enum `Result<_, OverflowError<usize>>`
               found enum `Result<_, OverflowError<u8>>`

error[E0308]: mismatched types
   --> /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aluvm-0.10.6/src/reg/indexes.rs:528:9
    |
527 |     fn try_from(value: Reg32) -> Result<Self, Self::Error> {
    |                                  ------------------------- expected `Result<Reg8, OverflowError>` because of return type
528 |         u3::try_from(value as u8).map(Reg8::from)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<Reg8, OverflowError>`, found `Result<Reg8, OverflowError<u8>>`
    |
    = note: expected enum `Result<_, OverflowError<usize>>`
               found enum `Result<_, OverflowError<u8>>`

error[E0308]: mismatched types
   --> /home/vincent/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aluvm-0.10.6/src/reg/indexes.rs:620:9
    |
619 |     fn try_from(value: Reg32) -> Result<Self, Self::Error> {
    |                                  ------------------------- expected `Result<RegS, OverflowError>` because of return type
620 |         u5::try_from(value as u8).map(RegS::from)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<RegS, OverflowError>`, found `Result<RegS, OverflowError<u8>>`
    |
    = note: expected enum `Result<_, OverflowError<usize>>`
               found enum `Result<_, OverflowError<u8>>`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `aluvm` (lib) due to 3 previous errors
warning: build failed, waiting for other jobs to finish..
```

Not sure why :/

the dependencies that I am using

```
# RGB and related
amplify = "=4.5.0"
base64 = "0.13.0"
bp-core = "=0.10.11"
commit_verify = "=0.10.6"
futures = "0.3"
hex = "0.4"
reqwest = { version = "0.11", default-features = false, features = ["json", "blocking"] }
rgb-contracts = { version = "=0.10.2", features = ["electrum"] }
rgb_core = { package = "rgb-core", version = "=0.10.8" }
rgb-lib = { git = "https://github.com/RGB-Tools/rgb-lib", branch = "rln_v0.10" }
rgb-std = "=0.10.9"
rgb-wallet = "=0.10.9"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0"
strict_encoding = "=2.6.1"
tokio = { version = "1.36", features = ["macros", "rt-multi-thread"] }
```

**Comment by dr-orlovsky** [comment]
Please compile using v0.11 branch

**Comment by storopoli** [comment]
I am hitting this in v0.11 also:

```shell
error[E0308]: mismatched types
   --> /Users/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aluvm-0.11.0-beta.2/src/reg/indexes.rs:624:9
    |
623 |     fn try_from(value: Reg32) -> Result<Self, Self::Error> {
    |                                  ------------------------- expected `Result<RegS, OverflowError>` because of return type
624 |         u5::try_from(value as u8).map(RegS::from)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Result<RegS, OverflowError>`, found `Result<RegS, OverflowError<u8>>`
    |
    = note: expected enum `Result<_, OverflowError<usize>>`
               found enum `Result<_, OverflowError<u8>>`
```

**Comment by vincenzopalazzo** [comment]
Hi @dr-orlovsky,

I do not think I can due that the dependence is not defined by me. I think if there is a bug in the 0.10.* we bump a new version in side https://crates.io/crates/rgb-core ?

**Comment by dr-orlovsky** [comment]
If you still experience problems please open an inssue in the repo which fails to compile - since it is not an issue related to AluVM
